language: python
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
before_script:
  - psql -c 'create database Drowsy;' -U postgres
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
install:
  - pip install -r requirements_test.txt
  - pip install coveralls
script:
  coverage run --source=drowsy -m pytest tests\ --db_types sqlite,postgres
after_success:
  coveralls
