language: python
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
  - sudo apt-get update
  - sudo apt-get -y install unixodbc-dev
before_script:
  - psql -c 'create database Drowsy;' -U postgres
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
install:
  - pip install -r requirements_test.txt
  - pip install coveralls
script:
  coverage run --source=drowsy -m pytest tests/ --db_types sqlite,postgres
after_success:
  coveralls
